### PR TITLE
Added -group and -commit-once options to overhead, added avg and total access time to search

### PR DESCRIPTION
**Pull request by gregtatcam**

### CODE REVIEW

**Comment by samoht** [comment]
I would like to run these scripts regularly: can you add a small script at the toplevel which run the commands with some good parameters and store the results in one of multiple files (maybe one per command)? Thanks!

**Comment by gregtatcam** [comment]
Sure, will do. Do you mean like a shell script? The ‘overhead’ doesn’t output anything, it creates a git repo with a bunch of messages. The idea is to see the storage overhead created by Irmin. I can dump ‘du -csh .git’ and the size of the original data. These two points are really the most interesting. Does this work?
I’ve done a bunch of testing on Irmin as I was looking to improve the mailbox structure. I think there are some interesting results. I’m writing it up and will send another email today or tomorrow.

**Comment by samoht** [comment]
yes a small shell scripts would be nice! And indeed, storing the result of `du -csh` and the input size is interesting: although I'm wondering if making `overhead` call `du -csh` directly would be easier.

**Comment by gregtatcam** [comment]
Ok, no pr. I’ll call ‘du’ as the system call.

**Comment by samoht** [comment]
Thanks!

**Comment by gregtatcam** [comment]
No, pr. Let me know if it matches what you need.

**Pull request merged**
